version: 2
jobs:
  build:
    docker:
      - image: movecrew/oven:latest
    steps:
      - checkout
      - run: wget https://raw.githubusercontent.com/redstarksten/kernel_xiaomi_ginkgo/10.0/circleci_build.sh
      - run: bash circleci_build.sh
